spring:

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ENTER CLIENT ID
            clientSecret: ENTER CLIENT SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: ENTER FACEBOOK CLIENT ID
            clientSecret: ENTER CLIENT SECRET 
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile



app:
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
